### ISSUE TITLE
Clarification needed?

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/macos-env-system#1]
In the Install Zsh section:

1. It is not clear whether/why students need to install Zsh if they're running Catalina
2. In Step 2, it says to run `echo $SHELL` but there's no indication of what it should return 
3. When I reopened the terminal in Step 7, I got this:

This is the Z Shell configuration function for new users, zsh-newuser-install.
You are seeing this message because you have no zsh startup files (the files .zshenv, .zprofile, .zshrc, .zlogin in the directory ~). This function can help you with a few settings that should make your use of the shell easier.

You can:

(q) Quit and do nothing.  The function will be run again next time.

(0) Exit, creating the file ~/.zshrc containing just a comment. That will prevent this function being run again.

(1) Continue to the main menu.

**Comment by maxwellbenton** [comment]
Hi @lizbur10!

I've updated the Zsh section to include:

```
If your version name is macOS Catalina (from the steps earlier), you should
already be using Zsh and can move on to **Check Your Work**.
```

and an additional step:

```
8. If you receive a message starting with "This is the Z Shell configuration
   function for new users, zsh-newuser-install", press `0`.
```

I believe this should clarify things for Catalina users.
